// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6WdqYyC0nHssRXzEGjl-3qTMvvb-xtfI',
    appId: '1:1049236040481:web:3932a7f279feac6d9a2c60',
    messagingSenderId: '1049236040481',
    projectId: 'onelovebeautysalon-29ec2',
    authDomain: 'onelovebeautysalon-29ec2.firebaseapp.com',
    storageBucket: 'onelovebeautysalon-29ec2.firebasestorage.app',
    measurementId: 'G-VEL11VXMRZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANpMZt9ikTs0mJrO4ba0pKkn3Nyhf4FeA',
    appId: '1:1049236040481:android:ef6e8b2191041bff9a2c60',
    messagingSenderId: '1049236040481',
    projectId: 'onelovebeautysalon-29ec2',
    storageBucket: 'onelovebeautysalon-29ec2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCql3Nr_WuuxFJTYxgF8NcNEmdP-fTY6O8',
    appId: '1:1049236040481:ios:0d76189528e95d359a2c60',
    messagingSenderId: '1049236040481',
    projectId: 'onelovebeautysalon-29ec2',
    storageBucket: 'onelovebeautysalon-29ec2.firebasestorage.app',
    iosBundleId: 'com.boda24.riderApp',
  );
}
