/// Firestore collection names and field name constants for 24Boda.
///
/// Why constants and not raw strings?
/// - A typo in a raw string like "shipemnts" fails silently at runtime —
///   you get an empty result instead of an error, and the bug is invisible.
/// - A typo in a constant like [FirestoreCollections.shipmants] fails at
///   compile time — the compiler catches it before the app ever runs.
/// - Renaming a collection means changing one constant, not hunting
///   through every file for every occurrence of the string.
///
/// Usage:
/// ```dart
/// FirebaseFirestore.instance
///   .collection(FirestoreCollections.users)
///   .doc(uid)
///   .get();
/// ```
abstract final class FirestoreCollections {
  // ── Top-level collections ─────────────────────────────────────────────────

  /// All platform users — customers, riders, and admins.
  /// Document ID = Firebase Auth UID.
  static const String users = 'users';

  /// Extended rider profiles.
  /// Document ID = same Firebase Auth UID as users/{uid}.
  static const String riders = 'riders';

  /// All delivery shipments.
  /// Document ID = auto-generated by Firestore.
  static const String shipments = 'shipments';
}

/// Field name constants for the [FirestoreCollections.users] collection.
///
/// Usage:
/// ```dart
/// .where(UserFields.role, isEqualTo: UserRole.customer.value)
/// ```
abstract final class UserFields {
  static const String id = 'id';
  static const String phone = 'phone';
  static const String role = 'role';
  static const String name = 'name';
  static const String profilePhotoUrl = 'profilePhotoUrl';
  static const String fcmToken = 'fcmToken';
  static const String isActive = 'isActive';
  static const String createdAt = 'createdAt';
  static const String updatedAt = 'updatedAt';
}

/// Field name constants for the [FirestoreCollections.riders] collection.
abstract final class RiderFields {
  static const String id = 'id';
  static const String vehicleType = 'vehicleType';
  static const String plateNumber = 'plateNumber';
  static const String idPhotoUrl = 'idPhotoUrl';
  static const String isApproved = 'isApproved';
  static const String isOnline = 'isOnline';
  static const String currentLocation = 'currentLocation';
  static const String rating = 'rating';
  static const String totalTrips = 'totalTrips';
  static const String totalEarnings = 'totalEarnings';
  static const String lastSeen = 'lastSeen';
  static const String createdAt = 'createdAt';
  static const String updatedAt = 'updatedAt';
}

/// Field name constants for the [FirestoreCollections.shipments] collection.
abstract final class ShipmentFields {
  static const String id = 'id';
  static const String customerId = 'customerId';
  static const String riderId = 'riderId';
  static const String status = 'status';
  static const String pickup = 'pickup';
  static const String dropoff = 'dropoff';
  static const String packageDescription = 'packageDescription';
  static const String packagePhotoUrl = 'packagePhotoUrl';
  static const String packageSize = 'packageSize';
  static const String customerNote = 'customerNote';
  static const String price = 'price';
  static const String distanceKm = 'distanceKm';
  static const String estimatedDurationMinutes = 'estimatedDurationMinutes';
  static const String customerRating = 'customerRating';
  static const String riderRating = 'riderRating';
  static const String createdAt = 'createdAt';
  static const String updatedAt = 'updatedAt';
  static const String acceptedAt = 'acceptedAt';
  static const String pickedUpAt = 'pickedUpAt';
  static const String deliveredAt = 'deliveredAt';
  static const String cancelledAt = 'cancelledAt';
}

/// Field name constants for the embedded [Location] object.
/// Used when querying nested fields e.g. pickup.lat
abstract final class LocationFields {
  static const String lat = 'lat';
  static const String lng = 'lng';
  static const String address = 'address';
  static const String contactPhone = 'contactPhone';
}

/// Field name constants for the embedded [ShipmentPrice] object.
abstract final class PriceFields {
  static const String estimatedFee = 'estimatedFee';
  static const String finalFee = 'finalFee';
  static const String riderEarnings = 'riderEarnings';
  static const String currency = 'currency';
}
